### ISSUE TITLE
Generates files that mattermost throws a ` bufio.Scanner: token too long` error for

### ISSUE THREAD

**Issue by cmmh** [mattermost/mmetl#1]
Scenario: 
Slack exported zip file with attachments, direct message, private channels. 

From Mattermost:  
Running Bulk Import Data Validation.
** This checks the validity of the entities in the data file, but does not persist any changes **
Use the --apply flag to perform the actual data import.

BulkImport: Error reading import data file., bufio.Scanner: token too long

**Comment by noxer** [comment]
Closed. The limits have since been raised. Feel free to reopen this if it still happens to you.
