### ISSUE TITLE
Installation not possible / remote: Repository not found

### ISSUE THREAD

**Issue by rottee** [mattermost/mmetl#2]
Looks like the project URL moved from mattermost to mgdelacroix.

go get -u github.com/mattermost/mmetl does not work, because repository can not found.

Also there are some dependencies/references to this url, which does not work.

remote: Repository not found.
fatal: repository 'https://github.com/mattermost/mmetl/' not found
package github.com/mattermost/mmetl: exit status 128

**Comment by mgdelacroix** [comment]
Thanks for reporting this issue @rottee! The repository has been moved to the `mattermost` organisation, so the `go get` command should work now.
